complex_encoder:
  tracking:
    which: ["epoch"]
    emb_tracking: True
  data:
    name: stgcn_50_classes
    path: ./content/
    verbose: True
  loader: 
    batch_size: 256
    shuffle: True
  loss: jsd
  print_summary: True
  encoder: 
    # [(c_in, c_out, spec_out, out, kernel)]
    architecture: [
      [ 2, 32, 64, 64, 36 ],
      [ 64, 64, 128, 128, 36 ],
      [ 128, 128, 256, 256, 36 ]
   ]
    residual: True
    discriminator_layer: False
    dropout: 0
  encoder_training:
    verbose: True
    n_epochs: 50
    optimizer_name: Adam
    optimizer:
      lr: 0.01
    # gradient_clipping: 0.2
  # classifier: 
  #   in_dim: 256
  #   hidden_layers: [128, 512, 256]
  # classifier_training:
  #   verbose: True
  #   n_epochs: 50
  #   optimizer_name: Adam
  #   optimizer:
  #     lr: 0.01
  #   gradient_clipping: 0.2
  
small_complex_encoder:
  data:
    name: stgcn_50_classes
    path: ./content/
    verbose: True
    lim: 2000
  loader:
    batch_size: 16
    shuffle: True
  stratify:
    num: 2
    lim: 100
  emb_tracking: 10
  loss: bce
  training:
    verbose: True
    n_epochs: 50
    optimizer_name: Adam
    optimizer:
      lr: 0.01

evaluate_experiment:
  exp:
    path: ./output/20012021_1303_debug_small_complex_encoder/
  mode: sklearn
  classifier: 
    in_dim: 256
    hidden_layers: [128, 512, 256]
  classifier_training:
    verbose: True
    n_epochs: 50
    optimizer_name: SGD
    optimizer:
      lr: 0.001
      momentum: 0.9
    gradient_clipping: 0.2
